alter table OFFICE_REQUEST_COMMUNICATION add constraint FK_OFFICE_REQUEST_COMMUNICATION_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table OFFICE_REQUEST_COMMUNICATION add constraint FK_OFFICE_REQUEST_COMMUNICATION_REQUEST foreign key (REQUEST_ID) references OFFICE_REQUEST(ID);
create index IDX_OFFICE_REQUEST_COMMUNICATION_REQUEST on OFFICE_REQUEST_COMMUNICATION (REQUEST_ID);
