alter table OFFICE_REQUEST_STEP add constraint FK_OFFICE_REQUEST_STEP_STEP foreign key (STEP_ID) references OFFICE_STEP(ID);
alter table OFFICE_REQUEST_STEP add constraint FK_OFFICE_REQUEST_STEP_USER foreign key (USER_ID) references SEC_USER(ID);
alter table OFFICE_REQUEST_STEP add constraint FK_OFFICE_REQUEST_STEP_REQUEST foreign key (REQUEST_ID) references OFFICE_REQUEST(ID);
create index IDX_OFFICE_REQUEST_STEP_STEP on OFFICE_REQUEST_STEP (STEP_ID);
create index IDX_OFFICE_REQUEST_STEP_USER on OFFICE_REQUEST_STEP (USER_ID);
create index IDX_OFFICE_REQUEST_STEP_REQUEST on OFFICE_REQUEST_STEP (REQUEST_ID);
