alter table OFFICE_REQUEST_STATUS add constraint FK_OFFICE_REQUEST_STATUS_STEP foreign key (STEP_ID) references OFFICE_STEP(ID);
create index IDX_OFFICE_REQUEST_STATUS_STEP on OFFICE_REQUEST_STATUS (STEP_ID);
