alter table OFFICE_POSITION_USER add constraint FK_OFFICE_POSITION_USER_POSITION foreign key (POSITION_ID) references OFFICE_POSITION(ID) on delete CASCADE;
alter table OFFICE_POSITION_USER add constraint FK_OFFICE_POSITION_USER_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_OFFICE_POSITION_USER_POSITION on OFFICE_POSITION_USER (POSITION_ID);
create index IDX_OFFICE_POSITION_USER_USER on OFFICE_POSITION_USER (USER_ID);
