alter table OFFICE_REQUEST_LOG add constraint FK_OFFICE_REQUEST_LOG_RECEPIENT foreign key (RECEPIENT_ID) references SEC_USER(ID);
create index IDX_OFFICE_REQUEST_LOG_RECEPIENT on OFFICE_REQUEST_LOG (RECEPIENT_ID);
