alter table OFFICE_REQUEST_STEP add constraint FK_OFFICE_REQUEST_STEP_POSITION foreign key (POSITION_ID) references OFFICE_POSITION(ID);
create index IDX_OFFICE_REQUEST_STEP_POSITION on OFFICE_REQUEST_STEP (POSITION_ID);
