alter table OFFICE_POSITION_ACTION add constraint FK_OFFICE_POSITION_ACTION_POSITION foreign key (POSITION_ID) references OFFICE_POSITION(ID) on delete CASCADE;
alter table OFFICE_POSITION_ACTION add constraint FK_OFFICE_POSITION_ACTION_TEMPLATE foreign key (TEMPLATE_ID) references SYS_FILE(ID);
create unique index IDX_OFFICE_POSITION_ACTION_UNIQ_TEMPLATE_ID on OFFICE_POSITION_ACTION (TEMPLATE_ID) ;
create index IDX_OFFICE_POSITION_ACTION_POSITION on OFFICE_POSITION_ACTION (POSITION_ID);
