alter table OFFICE_REQUEST_ACTION add constraint FK_OFFICE_REQUEST_ACTION_STEP foreign key (STEP_ID) references OFFICE_STEP(ID);
create index IDX_OFFICE_REQUEST_ACTION_STEP on OFFICE_REQUEST_ACTION (STEP_ID);
